app = 'zero-sample'
primary_region = 'nrt'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  method = "GET"
  timeout = "5s"
  interval = "10s"
  force_https = true
  processes = ['app']
  grace_period = "10s"
  internal_port = 3000
  min_machines_running = 1
  path = "/_zero/keepalive"
  auto_start_machines = true
  auto_stop_machines = 'stop'

[[vm]]
  cpus = 1
  memory_mb = 2048
  cpu_kind = 'shared'
